/**
 * Generate LQIP (Low Quality Image Placeholder) thumbnails
 * Creates tiny blurred previews (2-5 KB base64) for all images in LowResImages folder
 * 
 * Usage: node generate-lqip.js
 */

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const LOW_RES_IMAGES_FOLDER = path.join(__dirname, 'Images', 'LowResImages');
const OUTPUT_FILE = path.join(__dirname, 'api', 'lqip-data.js');

// Target size: 2-5 KB base64
const TARGET_SIZE_KB = 3; // Aim for 3 KB
const MAX_WIDTH = 20; // Tiny width for placeholder
const QUALITY = 0.3; // Low quality JPEG

async function generateLQIP(imagePath) {
    try {
        // Read image
        const image = sharp(imagePath);
        const metadata = await image.metadata();
        
        // Calculate dimensions to maintain aspect ratio
        const aspectRatio = metadata.width / metadata.height;
        const width = MAX_WIDTH;
        const height = Math.round(MAX_WIDTH / aspectRatio);
        
        // Generate tiny blurred version
        const buffer = await image
            .resize(width, height, {
                fit: 'inside',
                withoutEnlargement: true
            })
            .jpeg({ 
                quality: Math.round(QUALITY * 100),
                mozjpeg: true 
            })
            .blur(5) // Add blur for LQIP effect
            .toBuffer();
        
        // Convert to base64 data URL
        const base64 = buffer.toString('base64');
        const dataUrl = `data:image/jpeg;base64,${base64}`;
        
        // Check size
        const sizeKB = (dataUrl.length * 3) / 4 / 1024; // Approximate base64 size
        
        // If too large, reduce quality further
        if (sizeKB > TARGET_SIZE_KB * 1.5) {
            const reducedBuffer = await image
                .resize(Math.max(10, Math.round(width * 0.8)), Math.max(10, Math.round(height * 0.8)), {
                    fit: 'inside',
                    withoutEnlargement: true
                })
                .jpeg({ 
                    quality: Math.round(QUALITY * 50),
                    mozjpeg: true 
                })
                .blur(8)
                .toBuffer();
            
            const reducedBase64 = reducedBuffer.toString('base64');
            const reducedDataUrl = `data:image/jpeg;base64,${reducedBase64}`;
            const reducedSizeKB = (reducedDataUrl.length * 3) / 4 / 1024;
            
            return {
                dataUrl: reducedDataUrl,
                sizeKB: reducedSizeKB,
                width: Math.max(10, Math.round(width * 0.8)),
                height: Math.max(10, Math.round(height * 0.8))
            };
        }
        
        return {
            dataUrl: dataUrl,
            sizeKB: sizeKB,
            width: width,
            height: height
        };
    } catch (error) {
        console.error(`❌ Error generating LQIP for ${imagePath}:`, error.message);
        return null;
    }
}

async function generateAllLQIPs() {
    console.log('🚀 Starting LQIP generation...');
    console.log(`📁 Scanning folder: ${LOW_RES_IMAGES_FOLDER}`);
    
    // Check if folder exists
    if (!fs.existsSync(LOW_RES_IMAGES_FOLDER)) {
        console.error(`❌ Folder not found: ${LOW_RES_IMAGES_FOLDER}`);
        process.exit(1);
    }
    
    // Read all image files
    const files = fs.readdirSync(LOW_RES_IMAGES_FOLDER);
    const imageExtensions = ['.jpg', '.jpeg', '.png', '.webp'];
    const imageFiles = files.filter(file => {
        const ext = path.extname(file).toLowerCase();
        return imageExtensions.includes(ext);
    });
    
    console.log(`📸 Found ${imageFiles.length} images to process`);
    
    const lqipData = {};
    let processed = 0;
    let failed = 0;
    let totalSizeKB = 0;
    
    // Process each image
    for (const file of imageFiles) {
        const imagePath = path.join(LOW_RES_IMAGES_FOLDER, file);
        const relativePath = `Images/LowResImages/${file}`;
        
        console.log(`\n🔄 Processing: ${file}`);
        
        const result = await generateLQIP(imagePath);
        
        if (result) {
            lqipData[relativePath] = result.dataUrl;
            processed++;
            totalSizeKB += result.sizeKB;
            console.log(`   ✅ Generated: ${result.sizeKB.toFixed(2)} KB (${result.width}x${result.height})`);
        } else {
            failed++;
            console.log(`   ❌ Failed to generate LQIP`);
        }
    }
    
    // Generate JavaScript file
    const jsContent = `/**
 * LQIP (Low Quality Image Placeholder) Data
 * Auto-generated by generate-lqip.js
 * 
 * Contains base64-encoded tiny blurred previews (2-5 KB) for instant gallery loading
 * 
 * DO NOT EDIT MANUALLY - Regenerate using: node generate-lqip.js
 * 
 * Generated: ${new Date().toISOString()}
 * Total images: ${processed}
 * Average size: ${(totalSizeKB / processed).toFixed(2)} KB per placeholder
 */

const LQIP_DATA = ${JSON.stringify(lqipData, null, 2)};

module.exports = LQIP_DATA;
`;
    
    // Ensure api directory exists
    const apiDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(apiDir)) {
        fs.mkdirSync(apiDir, { recursive: true });
    }
    
    // Write to file
    fs.writeFileSync(OUTPUT_FILE, jsContent, 'utf8');
    
    console.log('\n' + '='.repeat(60));
    console.log('✅ LQIP Generation Complete!');
    console.log('='.repeat(60));
    console.log(`📊 Statistics:`);
    console.log(`   Processed: ${processed} images`);
    console.log(`   Failed: ${failed} images`);
    console.log(`   Total size: ${totalSizeKB.toFixed(2)} KB`);
    console.log(`   Average size: ${(totalSizeKB / processed).toFixed(2)} KB per placeholder`);
    console.log(`\n📄 Output file: ${OUTPUT_FILE}`);
    console.log(`\n💡 Next steps:`);
    console.log(`   1. The LQIP data is now available in api/lqip-data.js`);
    console.log(`   2. Import it in api/functions.js: const LQIP_DATA = require('./lqip-data');`);
    console.log(`   3. Use it in handleGetPhotos: placeholder: LQIP_DATA[lowResPath] || null`);
}

// Run if called directly
if (require.main === module) {
    generateAllLQIPs().catch(error => {
        console.error('❌ Fatal error:', error);
        process.exit(1);
    });
}

module.exports = { generateLQIP, generateAllLQIPs };
